MapleMooc/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import xadmin
from MapleMooc.settings import MEDIA_ROOT

from users.views import IndexView, ActiveUserView, ResetView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='user/index.html'), name='index'),
    path('', IndexView.as_view(), name='index'),
    path('user/', include('users.urls')),  # 用户
    path('org/', include('organizations.urls')),  # 机构
    path('course/', include('courses.urls')),  # 课程
    # path('teacher/', include('organizations.urls')),  # 讲师
    # 配置上传文件的访问处理
    re_path('media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}),
    path('xadmin/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),  # 验证码
    path('active/<active_code>/', ActiveUserView.as_view(), name='user_active'),
    # 重置密码urlc ：用来接收来自邮箱的重置链接
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name="reset_pwd"),

]

apps/courses/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @desc  : Created by San on 2018-07-11 10:32
# @site  : https://github.com/SunmoonSan
from django.urls import path, include, re_path

from .views import CourseListView, CourseDetailView, CourseInfoView, CourseCommentListView, CourseAddCommentView, \
    VideoPlayView

app_name='course'
urlpatterns = [
    # path('login/', LoginView.as_view(), name='login'),  # 登录
    path('list/', CourseListView.as_view(), name='course_list'),
    path('detail/<int:course_id>', CourseDetailView.as_view(), name='course_detail'),
    path('info/<int:course_id>', CourseInfoView.as_view(), name='course_info'),
    path('comment/<int:course_id>', CourseCommentListView.as_view(), name='course_comment_list'),
    path('add_comment', CourseAddCommentView.as_view(), name='course_add_comment'),
    path('video-play/<int:video_id>/', VideoPlayView.as_view(), name='video_play'),
]

apps/organizations/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @desc  : Created by San on 2018-07-11 10:40
# @site  : https://github.com/SunmoonSan
from django.urls import path

from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, TeacherListView, \
    TeacherDetailView, AddFavoriteView

app_name = 'org'
urlpatterns = [
    # 教师栏列表
    path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
    # 教师详情页
    path('teacher_detail/<int:teacher_id>/', TeacherDetailView.as_view(), name='teacher_detail'),
    # 机构列表
    path('list/', OrgView.as_view(), name='org_list'),
    path('add_ask/', AddUserAskView.as_view(), name='add_ask'),
    # home页面,取纯数字
    path('home/<int:org_id>/', OrgHomeView.as_view(), name="org_home"),
    # 访问课程
    path('course/<int:org_id>/', OrgCourseView.as_view(), name="org_course"),
    # 机构介绍
    path('desc/<int:org_id>/', OrgDescView.as_view(), name='org_desc'),
    # 机构教师
    path('teacher/<int:org_id>/', OrgTeacherView.as_view(), name='org_teacher'),
    # 添加收藏
    path('add_fav/', AddFavoriteView.as_view(), name='add_favorite'),

]

apps/users/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @desc  : Created by San on 2018-07-11 10:32
# @site  : https://github.com/SunmoonSan
from django.views.static import serve
from django.urls import path, include, re_path
from django.views.generic import TemplateView

import xadmin
from MapleMooc.settings import MEDIA_ROOT
from users.views import LoginView, ForgetPwdView, ResetView, ModifyPwdView, RegisterView, ActiveUserView, IndexView, \
    LogoutView, UserInfoView, UploadImageView, UpdatePwdView, MyCourseView, MyMessageView, MyFavoriteView

app_name = 'user'
urlpatterns = [

    path('login/', LoginView.as_view(), name='login'),  # 登录
    path('logout/', LogoutView.as_view(), name='logout'),  # 退出
    path('register/', RegisterView.as_view(), name='register'),  # 注册
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    path('reset/', ResetView.as_view(), name='reset_pwd'),
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
    path('info/', UserInfoView.as_view(), name='user_info'),
    # 上传用户头像
    path('image/upload/', UploadImageView.as_view(), name='image_upload'),
    path('update/pwd/', UpdatePwdView.as_view(), name="update_pwd"),
    # 我的课程
    path('my_course/', MyCourseView.as_view(), name='my_course'),
    # 我的收藏
    path('my_favorite/', MyFavoriteView.as_view(), name='my_favorite'),
    path('my_favorite/<int:fav_type>', MyFavoriteView.as_view()),
    # 我的消息
    path('my_message/', MyMessageView.as_view(), name='my_message'),
    path('xadmin/', xadmin.site.urls),
    path('active/<active_code>/', ActiveUserView.as_view(), name='user_active'),

]

apps/courses/models.py
from django.db import models
from django.utils import timezone

from organizations.models import Teacher, CourseOrg


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name=u"所属机构", null=True, blank=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name=u"讲师", null=True, blank=True)

    name = models.CharField(max_length=50, verbose_name=u'课程名')
    desc = models.CharField(max_length=300, verbose_name=u'课程描述')
    detail = models.TextField(verbose_name=u'课程详情', default='')
    is_banner = models.BooleanField(default=False, verbose_name='是否是轮播图')
    degree = models.CharField(max_length=20, choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')), verbose_name=u'课程难度')
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长(分钟)')
    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    fav_num = models.IntegerField(default=0, verbose_name=u'收藏人数')
    you_need_know = models.CharField(max_length=300, default=u"一颗勤学的心是本课程必要前提", verbose_name=u"课程须知")
    teacher_tell = models.CharField(max_length=300, default=u"什么都可以学到,按时交作业,不然叫家长", verbose_name=u"老师告诉你")
    image = models.ImageField(upload_to='course/%Y/%m', verbose_name=u'封面')
    click_nums = models.IntegerField(default=0, verbose_name=u'点击数')
    category = models.CharField(max_length=20, verbose_name='课程类别', default='')
    tag = models.CharField(max_length=15, verbose_name='课程标签', default='')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u'章节名')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》课程的章节 >> {1}'.format(self.course, self.name)


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u'章节', on_delete=models.CASCADE)
    url = models.CharField(max_length=200, default="", verbose_name=u"访问地址")
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}章节的视频>>{1}'.format(self.lesson, self.name)


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u'课程')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name=u'资源文件', max_length=100)
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/course/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    课程评论
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}"/>
{% endblock %}

{% block nav_index %}
    <nav>
        <div class="nav">
            <div class="wp">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a></li>
                    <li class="active">
                        <a href="{% url 'course:course_list' %}">
                            公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                        </a>
                    </li>
                    <li>
                        <a href="teachers-list.html">授课教师</a>
                    </li>
                    <li><a href="{% url 'org:org_list' %}">授课机构</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block navigation %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
                    <li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                    <li>课程评论</li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

{% block content %}
    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.learn_times }}分钟</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.students }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active " id="learnOn" href="{% url 'course:course_info' course.id %}"><span>章节</span></a>
                                </li>
                                <li><a id="commentOn" class="active" href="{% url 'course:course_comment_list' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>

                        <!--发布评论-->
                        <div id="js-pub-container" class="issques clearfix js-form">
                            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                                <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
                            </div>
                            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                            <p class="global-errortip js-global-error"></p>
                        </div>
                        <div id="course_note">
                            <ul class="mod-post" id="comment-list">

                                {% for comment in all_comments %}
                                    <li class="post-row">
                                        <div class="media">
                                        <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.user.image }}'
                                                                   width='40' height='40'/></span>
                                        </div>
                                        <div class="bd">
                                            <div class="tit">
                                                <span target="_blank">{{ comment.user.username }}</span>
                                            </div>
                                            <p class="cnt">
                                                {{ comment.comments }}
                                            </p>
                                            <div class="footer clearfix">
                                                <span title="创建时间" class="l timeago">评论时间：{{ comment.add_time }}</span>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}

                            </ul>
                        </div>

                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">

                                    <li>
                                        <span><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;前端页面</span>
                                        <a href="../media/course/resource/2016/11/media.zip" class="downcode"
                                           target="_blank" download="" data-id="274" title="">下载</a>
                                    </li>

                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="/u/315464/courses?sort=publish" target="_blank">
                                        <img src='../media/teacher/2016/11/aobama_CXWwMef.png' width='80' height='80'/>
                                    </a>
                                    <span class="tit">
                                        <a href="/u/315464/courses?sort=publish" target="_blank">bobby</a>
                                    </span>
                                    <span class="job">xxx</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">python基础你需要有</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">django的进阶开发</dd>
                                    </dl>
                                </div>
                            </div>


                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            <li class="curr">
                                                <a href="/view/85?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/57035ff200014b8a06000338-240-135.jpg"
                                                         alt="Java入门第一季">
                                                    <span class="name autowrap">Java入门第一季</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/view/110?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/5703604a0001694406000338-240-135.jpg"
                                                         alt="Java入门第三季">
                                                    <span class="name autowrap">Java入门第三季</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/view/124?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/570360620001390f06000338-240-135.jpg"
                                                         alt="Java入门第二季">
                                                    <span class="name autowrap">Java入门第二季</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/view/47?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/570765d90001bf1406000338-240-135.jpg"
                                                         alt="Spring MVC起步">
                                                    <span class="name autowrap">Spring MVC起步</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/view/36?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/53e1d0470001ad1e06000338-240-135.jpg"
                                                         alt="JavaScript入门篇">
                                                    <span class="name autowrap">JavaScript入门篇</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                        <ul class="other-list">
                                            <li class="curr">
                                                <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg"
                                                         alt="Java工程师">
                                                    <span class="name autowrap">Java工程师</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        //添加评论
        $('#js-pl-submit').on('click', function () {
            let comments = $("#js-pl-textarea").val();
            if (comments === "") {
                alert("评论不能为空");
                return
            }
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'course:course_add_comment' %}",
                data: {'course_id':{{ course.id }}, 'comments': comments},
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status === 'fail') {
                        if (data.msg === '用户未登录') {
                            window.location.href = "{% url 'user:login' %}";
                        } else {
                            alert(data.msg)
                        }

                    } else if (data.status === 'success') {
                        window.location.reload();//刷新当前页面.
                    }
                },
            });
        });

    </script>
{% endblock %}

templates/course/course-list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block nav_index %}
    <nav>
        <div class="nav">
            <div class="wp">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a></li>
                    <li class="active">
                        <a href="{% url 'course:course_list' %}">
                            公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'org:teacher_list' %}">授课教师</a>
                    </li>
                    <li><a href="{% url 'org:org_list' %}">授课机构</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block navigation %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <div class="list" style="margin-top:0;">
                <div class="left layout">
                    <div class="head">
                        <ul class="tab_header">
                            {#                            <li class="{% ifequal sort "" %}active{% endifequal %}"><a#}
                            {#                                    href="?sort=&keywords={{ search_keywords }}">最新 </a></li>#}
                            {#                            <li class="{% ifequal sort "hot" %}active{% endifequal %}"><a#}
                            {#                                    href="?sort=hot&keywords={{ search_keywords }}">最热门</a></li>#}
                            {#                            <li class="{% ifequal sort "students" %}active{% endifequal %}"><a#}
                            {#                                    href="?sort=students&keywords={{ search_keywords }}">参与人数</a></li>#}

                            <li class="{% ifequal sort "" %}active{% endifequal %}"><a href="?sort=">最新 </a></li>
                            <li class="{% ifequal sort "hot" %}active{% endifequal %}"><a href="?sort=hot">最热门</a></li>
                            <li class="{% ifequal sort "students" %}active{% endifequal %}"><a href="?sort=students">参与人数</a>
                            </li>
                        </ul>
                    </div>
                    <div id="inWindow">
                        <div class="tab_cont " id="content">
                            <div class="group_list">

                                {% for course in all_courses.object_list %}
                                    <div class="box">
                                        <a href="{% url 'course:course_detail' course.id %}">
                                            <img width="280" height="350" class="scrollLoading"
                                                 src="{{ MEDIA_URL }}{{ course.image }}"/>
                                        </a>
                                        <div class="des">
                                            <a href="">
                                                <h2>{{ course.name }}</h2>
                                            </a>
                                            <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                            <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                        </div>
                                        <div class="bottom">
                                            <a href="{% url 'course:course_detail' course.id %}"><span
                                                    class="fl">来自{{ course.org_set.name }}</span></a>
                                            <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.fav_num }}
                                    </span>
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                            <div class="pageturn">
                                <ul class="pagelist">


                                    {# 分页 #}
                                    <ul class="pagelist">
                                        {% if all_courses.has_previous %}
                                            <li class="long"><a
                                                    href="?{{ all_courses.previous_page_number.querystring }}">上一页</a>
                                            </li>
                                        {% endif %}
                                        {% for page in all_courses.pages %}
                                            {% if page %}
                                                {% ifequal page all_courses.number %}
                                                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a>
                                                    </li>
                                                {% else %}
                                                    <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                                {% endifequal %}
                                            {% else %}
                                                <li class="none"><a href="">...</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if all_courses.has_next %}
                                            <li class="long"><a
                                                    href="?{{ all_courses.next_page_number.querystring }}">下一页</a></li>
                                        {% endif %}
                                    </ul>


                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="right layout">
                    <div class="head">热门课程推荐</div>
                    <div class="group_recommend">

                        {% for hot_cours in hot_courses %}
                            <dl>
                                <dt>
                                    <a target="_blank" href="">
                                        <img width="240" height="220" class="scrollLoading"
                                             src="{{ MEDIA_URL }}{{ hot_cours.image }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <a target="_blank" href=""><h2>{{ hot_cours.name }}</h2></a>
                                    <span class="fl">难度：<i class="key">{{ hot_cours.get_degree_display }}</i></span>
                                    {# 用以显示初级, 高级 #}
                                </dd>
                            </dl>
                        {% endfor %}




                        {% comment %}<dl>
                            <dt>
                                <a target="_blank" href="">
                                    <img width="240" height="220" class="scrollLoading"
                                         src="../media/courses/2016/12/python面向对象.jpg"/>
                                </a>
                            </dt>
                            <dd>
                                <a target="_blank" href=""><h2> python面向对象</h2></a>
                                <span class="fl">难度：<i class="key">中级</i></span>
                            </dd>
                        </dl>

                        <dl>
                            <dt>
                                <a target="_blank" href="">
                                    <img width="240" height="220" class="scrollLoading"
                                         src="../media/courses/2016/12/python文件处理.jpg"/>
                                </a>
                            </dt>
                            <dd>
                                <a target="_blank" href=""><h2> python文件处理</h2></a>
                                <span class="fl">难度：<i class="key">中级</i></span>
                            </dd>
                        </dl>{% endcomment %}


                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}