MapleMooc/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import xadmin
from MapleMooc.settings import MEDIA_ROOT

from users.views import IndexView, ActiveUserView, ResetView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='user/index.html'), name='index'),
    path('', IndexView.as_view(), name='index'),
    path('user/', include('users.urls')),  # 用户
    path('org/', include('organizations.urls')),  # 机构
    path('course/', include('courses.urls')),  # 课程
    # path('teacher/', include('organizations.urls')),  # 讲师
    # 配置上传文件的访问处理
    re_path('media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}),
    path('xadmin/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),  # 验证码
    path('active/<active_code>/', ActiveUserView.as_view(), name='user_active'),
    # 重置密码urlc ：用来接收来自邮箱的重置链接
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name="reset_pwd"),

]

apps/courses/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @desc  : Created by San on 2018-07-11 10:32
# @site  : https://github.com/SunmoonSan
from django.urls import path, include, re_path

from .views import CourseListView, CourseDetailView, CourseInfoView, CourseCommentListView, CourseAddCommentView, \
    VideoPlayView

app_name='course'
urlpatterns = [
    # path('login/', LoginView.as_view(), name='login'),  # 登录
    path('list/', CourseListView.as_view(), name='course_list'),
    path('detail/<int:course_id>', CourseDetailView.as_view(), name='course_detail'),
    path('info/<int:course_id>', CourseInfoView.as_view(), name='course_info'),
    path('comment/<int:course_id>', CourseCommentListView.as_view(), name='course_comment_list'),
    path('add_comment', CourseAddCommentView.as_view(), name='course_add_comment'),
    path('video-play/<int:video_id>/', VideoPlayView.as_view(), name='video_play'),
]

apps/organizations/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @desc  : Created by San on 2018-07-11 10:40
# @site  : https://github.com/SunmoonSan
from django.urls import path

from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, TeacherListView, \
    TeacherDetailView, AddFavoriteView

app_name = 'org'
urlpatterns = [
    # 教师栏列表
    path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
    # 教师详情页
    path('teacher_detail/<int:teacher_id>/', TeacherDetailView.as_view(), name='teacher_detail'),
    # 机构列表
    path('list/', OrgView.as_view(), name='org_list'),
    path('add_ask/', AddUserAskView.as_view(), name='add_ask'),
    # home页面,取纯数字
    path('home/<int:org_id>/', OrgHomeView.as_view(), name="org_home"),
    # 访问课程
    path('course/<int:org_id>/', OrgCourseView.as_view(), name="org_course"),
    # 机构介绍
    path('desc/<int:org_id>/', OrgDescView.as_view(), name='org_desc'),
    # 机构教师
    path('teacher/<int:org_id>/', OrgTeacherView.as_view(), name='org_teacher'),
    # 添加收藏
    path('add_fav/', AddFavoriteView.as_view(), name='add_favorite'),

]

apps/users/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @desc  : Created by San on 2018-07-11 10:32
# @site  : https://github.com/SunmoonSan
from django.views.static import serve
from django.urls import path, include, re_path
from django.views.generic import TemplateView

import xadmin
from MapleMooc.settings import MEDIA_ROOT
from users.views import LoginView, ForgetPwdView, ResetView, ModifyPwdView, RegisterView, ActiveUserView, IndexView, \
    LogoutView, UserInfoView, UploadImageView, UpdatePwdView, MyCourseView, MyMessageView, MyFavoriteView

app_name = 'user'
urlpatterns = [

    path('login/', LoginView.as_view(), name='login'),  # 登录
    path('logout/', LogoutView.as_view(), name='logout'),  # 退出
    path('register/', RegisterView.as_view(), name='register'),  # 注册
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    path('reset/', ResetView.as_view(), name='reset_pwd'),
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
    path('info/', UserInfoView.as_view(), name='user_info'),
    # 上传用户头像
    path('image/upload/', UploadImageView.as_view(), name='image_upload'),
    path('update/pwd/', UpdatePwdView.as_view(), name="update_pwd"),
    # 我的课程
    path('my_course/', MyCourseView.as_view(), name='my_course'),
    # 我的收藏
    path('my_favorite/', MyFavoriteView.as_view(), name='my_favorite'),
    path('my_favorite/<int:fav_type>', MyFavoriteView.as_view()),
    # 我的消息
    path('my_message/', MyMessageView.as_view(), name='my_message'),
    path('xadmin/', xadmin.site.urls),
    path('active/<active_code>/', ActiveUserView.as_view(), name='user_active'),

]

apps/courses/models.py
from django.db import models
from django.utils import timezone

from organizations.models import Teacher, CourseOrg


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name=u"所属机构", null=True, blank=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name=u"讲师", null=True, blank=True)

    name = models.CharField(max_length=50, verbose_name=u'课程名')
    desc = models.CharField(max_length=300, verbose_name=u'课程描述')
    detail = models.TextField(verbose_name=u'课程详情', default='')
    is_banner = models.BooleanField(default=False, verbose_name='是否是轮播图')
    degree = models.CharField(max_length=20, choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')), verbose_name=u'课程难度')
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长(分钟)')
    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    fav_num = models.IntegerField(default=0, verbose_name=u'收藏人数')
    you_need_know = models.CharField(max_length=300, default=u"一颗勤学的心是本课程必要前提", verbose_name=u"课程须知")
    teacher_tell = models.CharField(max_length=300, default=u"什么都可以学到,按时交作业,不然叫家长", verbose_name=u"老师告诉你")
    image = models.ImageField(upload_to='course/%Y/%m', verbose_name=u'封面')
    click_nums = models.IntegerField(default=0, verbose_name=u'点击数')
    category = models.CharField(max_length=20, verbose_name='课程类别', default='')
    tag = models.CharField(max_length=15, verbose_name='课程标签', default='')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u'章节名')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》课程的章节 >> {1}'.format(self.course, self.name)


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u'章节', on_delete=models.CASCADE)
    url = models.CharField(max_length=200, default="", verbose_name=u"访问地址")
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}章节的视频>>{1}'.format(self.lesson, self.name)


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u'课程')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name=u'资源文件', max_length=100)
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class UserProfile(AbstractUser):
    # 自定义的性别选择规则
    GENDER_CHOICES = (
        ("male", u"男"),
        ("female", u"女")
    )

    nickname = models.CharField(max_length=50, verbose_name=u'昵称', default='')
    birthday = models.DateField(verbose_name=u'生日', null=True, blank=True)
    gender = models.CharField(max_length=8, choices=GENDER_CHOICES, default='female')
    address = models.CharField(max_length=100, default=u'')
    mobile = models.CharField(max_length=11, null=True, blank=True)
    image = models.ImageField(max_length=100, upload_to="image/%Y/%m", default=u'image/default.png')

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=20, verbose_name=u'验证码')
    email = models.EmailField(max_length=50, verbose_name=u'邮箱')
    send_type = models.CharField(choices=(('register', u'注册'), ('forget', u'找回密码')), max_length=20, verbose_name=u'类型')
    send_time = models.DateTimeField(auto_now_add=True, verbose_name=u'时间')

    class Meta:
        verbose_name = u'邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}{1})'.format(self.code, self.email)


class Banner(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'标题')
    image = models.ImageField(upload_to='banner/%Y/%m', verbose_name=u'轮播图')
    url = models.URLField(max_length=200, verbose_name=u'访问地址')
    index = models.IntegerField(default=100, verbose_name=u'顺序')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'轮播图'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

apps/users/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @desc  : Created by San on 2018-07-10 15:02
# @site  : https://github.com/SunmoonSan
from django import forms
from captcha.fields import CaptchaField


# 登录表单
from users.models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)


# 注册表单
class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误'})  # 验证码


# 忘记密码表单
class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误'})  # 验证码


class ActiveForm(forms.Form):
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


# 重置密码表单
class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)


# 用户头像表单
class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


# 用户信息表单
class UserInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['nickname', 'gender', 'birthday', 'address', 'mobile']

templates/user/forgetpwd.html
{% extends 'user/user-base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="login-box clearfix">
        <div class="hd-login clearfix">
            <a class="index-logo" href="index.html"></a>
            <h1>忘记密码</h1>
            <a class="index-font" href="index.html">回到首页</a>
        </div>
        <div class="fl slide">
            <div class="imgslide">
                <ul class="imgs">
                    <li><a href=""><img width="483" height="472"
                                        src="{% static 'images/57a801860001c34b12000460.jpg' %}"/></a></li>
                    <li><a href=""><img width="483" height="472"
                                        src="{% static 'images/57a801860001c34b12000460.jpg' %}"/></a></li>
                    <li><a href=""><img width="483" height="472"
                                        src="{% static 'images/57a801860001c34b12000460.jpg' %}"/></a></li>
                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>
        <div class="fl form-box">
            <h2>忘记密码</h2>
            <form id="jsFindPwdForm" method="post" action="{% url 'user:forget_pwd' %}" autocomplete="off">
                <div class="form-group marb20 {% if forget_form.email.errors %} errorput{% endif %} ">
                    <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                    <input type="text" id="account" name="email" placeholder="邮箱"/>
                </div>
                <div class="form-group captcha1 marb38 {% if forget_form.captcha.errors %} errorput{% endif %}">
                    <label>验&nbsp;证&nbsp;码</label>
                    {{ forget_form.captcha }}{{ active_form.captcha }}
                </div>
                <div class="error btns" id="jsForgetTips">
                    {% for key, error in forget_form.errors.items %}{{ error }}{% endfor %}{{ msg }}</div>
                <input type="hidden" name="sms_type" value="1">
                <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交"/>
                <p class="form-p" style="bottom:40px;">您还可以<a href="{% url 'user:login' %}"> [直接登录]</a></p>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

templates/user/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    课程机构列表 - 慕学在线网
{% endblock %}

{% block nav_index %}
    <nav>
        <div class="nav">
            <div class="wp">
                <ul>
                    <li class="active"><a href="{% url 'index' %}">首页</a></li>
                    <li>
                        <a href="{% url 'course:course_list' %}">
                            公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'org:teacher_list' %}">授课教师</a>
                    </li>
                    <li><a href="{% url 'org:org_list' %}">授课机构</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block banner %}
    <div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in all_banner %}
                            <li>
                                <a href="{{ banner.url }}">
                                    <img width="1200" height="478"
                                         src="{{ MEDIA_URL }}{{ banner.image }}"/>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>

        </div>
    </div>
{% endblock %}

{% block feature %}
    <section>
        <div class="wp">
            <ul class="feature">
                <li class="feature1">
                    <img class="pic" src="{% static 'images/feature1.png' %}"/>
                    <p class="center">专业权威</p>
                </li>
                <li class="feature2">
                    <img class="pic" src="{% static 'images/feature2.png' %}"/>
                    <p class="center">课程最新</p>
                </li>
                <li class="feature3">
                    <img class="pic" src="{% static 'images/feature3.png' %}"/>
                    <p class="center">名师授课</p>
                </li>
                <li class="feature4">
                    <img class="pic" src="{% static 'images/feature4.png' %}"/>
                    <p class="center">数据真实</p>
                </li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
    <section>
        <div class="module">
            <div class="wp">
                <h1>公开课程</h1>
                <div class="module1 eachmod">
                    <div class="module1_1 left">
                        <img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
                        <p class="fisrt_word">名师授课<br/>专业权威</p>
                        <a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
                    </div>
                    <div class="right group_list">
                        <div class="module1_2 box">
                            <div class="imgslide2">
                                <ul class="imgs">
                                    {% for banner_cours in banner_courses %}
                                        <li>
                                            <a href="{% url 'course:course_detail' banner_cours.id %}">
                                                <img width="470" height="300"
                                                     src="{{ MEDIA_URL }}{{ banner_cours.image }}"/>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="unslider-arrow2 prev"></div>
                            <div class="unslider-arrow2 next"></div>
                        </div>
                        {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">  {# |add:2 #}
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190"
                                         src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="python入门2">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="慕课网666">{{ course.course_org }}</span>
                                    <span class="star fr">0</span>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="module greybg">
            <div class="wp">
                <h1>课程机构</h1>
                <div class="module3 eachmod">
                    <div class="module3_1 left">
                        <img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
                        <p class="fisrt_word">名校来袭<br/>权威认证</p>
                        <a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
                    </div>
                    <div class="right">
                        <ul>
                            {% for course_org in course_orgs %}
                                <li class="">
                                    <a href="{% url 'org:org_home' course_org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>全国知名</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="慕课网">{{ course_org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/user/login.html
{% extends 'user/user-base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="login-box clearfix">
        <div class="hd-login clearfix">
            <a class="index-logo" href="index.html"></a>
            <h1>用户登录</h1>
            <a class="index-font" href="index.html">回到首页</a>
        </div>
        <div class="fl slide">
            <div class="imgslide">
                <ul class="imgs">
                    <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
                    <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
                    <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>
        <div class="fl form-box">
            <h2>帐号登录</h2>
            <form action="{% url 'user:login' %}" method="post" autocomplete="off">
                <div class="form-group marb20 {% if login_form.username.errors %} errorput{% endif %}">
                    <label>用&nbsp;户&nbsp;名</label>
                    <input name="username" id="account_l" type="text" placeholder="手机号/邮箱"/>
                </div>
                <div class="form-group marb8 {% if login_form.password.errors %} errorput{% endif %}">
                    <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                    <input name="password" id="password_l" type="password" placeholder="请输入您的密码"/>
                </div>
                <div class="error btns login-form-tips" id="jsLoginTips">
                    {% for key, error in login_form.errors.items %}
                        {{ error }}
                    {% endfor %}
                    {{ msg }}
                </div>
                <div class="auto-box marb38">

                    <a class="fr" href="{% url "user:forget_pwd" %}">忘记密码？</a>
                </div>
                <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > "/>
                <input type="hidden" name="next" value="{{ redirect_url }}"/>
                {% csrf_token %}
            </form>
            {#                <p class="form-p">没有慕学在线网帐号？<a href="register.html">[立即注册]</a></p>#}
        </div>
    </div>
{% endblock %}

templates/user/register.html
{% extends 'user/user-base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="login-box clearfix">
        <div class="hd-login clearfix">
            <a class="index-logo" href="index.html"></a>
            <h1>用户注册</h1>
            <a class="index-font" href="index.html">回到首页</a>
        </div>
        <div class="fl slide">
            <div class="imgslide">
                <ul class="imgs">

                    <li><a href=""><img width="483" height="472"
                                        src="{% static 'images/57a801860001c34b12000460.jpg' %}"/></a></li>

                    <li><a href=""><img width="483" height="472"
                                        src="{% static 'images/57a801860001c34b12000460.jpg' %}"/></a></li>

                    <li><a href=""><img width="483" height="472"
                                        src="{% static 'images/57a801860001c34b12000460.jpg' %}"/></a></li>

                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>
        <div class="fl form-box">
            <div class="tab">
                <!--<h2 class="active">手机注册</h2>-->
                <h2>邮箱注册</h2>
            </div>

            <div class="tab-form">
                <form id="email_register_form" method="post" action="{% url 'user:register' %}" autocomplete="off">
                    <div class="form-group marb20 {% if register_form.email.errors %} errorput{% endif %}">
                        <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                        <input type="text" id="id_email" name="email"
                               placeholder="请输入您的邮箱地址"/>
                    </div>
                    <div class="form-group marb8 {% if register_form.password.errors %} errorput{% endif %}">
                        <label for="id_password">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                        <input type="password" id="id_password" name="password"/>
                    </div>
                    <div class="form-group marb8 captcha1 {% if register_form.captcha.errors %} errorput{% endif %}">
                        <label>验&nbsp;证&nbsp;码</label>
                        {{ register_form.captcha }}
                        {{ active_form.captcha }}
                    </div>
                    <div class="error btns" id="jsEmailTips">
                        {% for key, error in register_form.errors.items %}{{ error }}{% endfor %}{{ msg }}</div>
                    <div class="auto-box marb8">
                    </div>
                    <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录"/>
                    {% csrf_token %}
                </form>
            </div>
            <p class="form-p">已有账号？<a href="{% url 'user:login' %}">[立即登录]</a></p>
        </div>
    </div>
{% endblock %}

templates/user/user-base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>慕学在线网登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<div class="dialog" id="jsDialog">
<!--提示弹出框-->
<div class="successbox dialogbox" id="jsSuccessTips">
    <h1>成功提交</h1>
    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
    <div class="cont">
        <h2>您的需求提交成功！</h2>
        <p></p>
    </div>
</div>
<div  class="noactivebox dialogbox" id="jsUnactiveForm" >
    {% comment %}<h1>邮件验证提示</h1>
    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
    <div class="center">
        <img src="{% static 'images/send.png' %}"/>
        <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
        <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
        <p class="zy_success upmove"></p>
{#        <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>#}
        <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
    </div>{% endcomment %}
</div>
</div>
<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li class="active"><a href="{% url 'user:login' %}">[登录]</a></li>
                <li><a href="{% url 'user:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
    {% block content %}

    {% endblock %}

    </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/user/usercenter-fav-course.html
{% extends 'user/user-center-base.html' %}
{% load staticfiles %}
{% block title %}
    课程收藏
{% endblock %}

{% block navigation %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">

            <div class="head">
                <ul class="tab_header messagehead">
                    <li><a href="?fav_type=2">课程机构</a></li>
                    <li><a href="?fav_type=3">授课教师 </a></li>
                    <li class="active"><a href="?fav_type=1">公开课程</a></li>
                </ul>

            </div>

            <div class="companycenter">
                <div class="group_list brief">

                    {% for cours in courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' cours.id %}">
                                <img width="214" height="190"
                                     src="{{ MEDIA_URL }}{{ cours.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' cours.id %}"><h2>{{ cours.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ cours.learn_times }}min</i></span>
                                <span class="fr">学习人数：{{ cours.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ cours.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}